version: "3.9"

services:
  grafana:
    image: grafana/grafana:10.4.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
      - loki
      - jaeger

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
    depends_on:
      - consul

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # Jaeger UI (opsional)
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

  collector:
    image: otel/opentelemetry-collector:0.102.0
    container_name: otel-collector
    command: ["--config=/etc/otel/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel/otel-collector.yaml:ro
    ports:
      - "4319:4317" # optional expose (host)
      - "4320:4318"
      - "8889:8889" # Prometheus scrape
    depends_on:
      - jaeger
      - loki

  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  vector:
    image: timberio/vector:0.51.0-alpine
    container_name: vector
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
      - ./logs:/var/log/app
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
