global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["collector:8889"]
  - job_name: tempo
    static_configs:
      - targets: ["tempo:3200"]
